In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

from torch.utils.data import Dataset, DataLoader

In [20]:
x, y = make_classification(
    n_samples=3000, # THe # of data
    n_features=5, # depelent
    n_informative=2,
    n_redundant=0,
    n_clusters_per_class = 1,
    random_state=42
)

print(len(x))
print(x)
print(len(y))
print(y)
print(sum(y))

3000
[[-0.02439857 -0.57540077  1.26796049 -1.42222965 -0.9629849 ]
 [-1.07638119  0.3872175   1.08299994 -0.67379011 -2.65098736]
 [-1.12984986 -0.26922916  1.12735009 -0.82383687 -1.70574586]
 ...
 [-0.53797853  0.26401859 -0.48915618  0.4664446  -1.57451325]
 [ 0.01920342  0.9761859  -0.14717165 -1.51725386  2.31873002]
 [-0.37051336  0.93603022 -0.62133172 -0.23084897  1.66473405]]
3000
[0 0 0 ... 0 1 1]
1497


In [21]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(len(X_test), len(X_train), len(y_test), len(y_train))
print(sum(y_test))

600 2400 600 2400
309


In [22]:
class MyCustomData (Dataset):
    def __init__(self, x, y):
        self.x= torch.tensor(x, dtype=torch.float32)
        self.y= torch.tensor(y, dtype=torch.float32)
        
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

    def __len__(self):
        return len(self.x)

train_dataset = MyCustomData(X_train, y_train)
test_dataset = MyCustomData(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

# for i in test_loader :
#     print(i)
    
for idx, (datas, labels) in enumerate(train_loader):
    pass
    # print(idx, datas, labels)

In [23]:
class LogisticRegression(nn.Module):
    def __init__(self, input_dim):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_dim, 1)
        
    def forward(self, x):
        out = self.linear(x)
        out = torch.sigmoid(out)
        
        return out
    
model = LogisticRegression(input_dim=5)
print(model)

LogisticRegression(
  (linear): Linear(in_features=5, out_features=1, bias=True)
)


In [24]:
# !pip install adamp
from adamp import SGDP

criterion = nn.BCELoss()
optimizer = SGDP(model.parameters(), lr=0.01, weight_decay=1e-5, momentum=0.9, nesterov=True)
print(optimizer)

SGDP (
Parameter Group 0
    dampening: 0
    delta: 0.1
    eps: 1e-08
    lr: 0.01
    momentum: 0.9
    nesterov: True
    wd_ratio: 0.1
    weight_decay: 1e-05
)


### train loop

In [25]:
num_epochs = 100

for epoch in range(num_epochs):
    for inputs, targets in train_loader:
        # print(targets)
        # print(targets.unsqueeze(1))
        
        
        optimizer.zero_grad()
        
        outputs = model(inputs)
        loss = criterion(outputs, targets.unsqueeze(1))
        loss.backward()
        
        optimizer.step()
        
    if epoch % 10 == 0 :
        print(f"Epoch:[{epoch+1}/{num_epochs}], Loss : [{loss.item():.4f}]")
        

Epoch:[1/100], Loss : [0.3164]
Epoch:[11/100], Loss : [0.2027]
Epoch:[21/100], Loss : [0.2203]
Epoch:[31/100], Loss : [0.2004]
Epoch:[41/100], Loss : [0.4030]
Epoch:[51/100], Loss : [0.2357]
Epoch:[61/100], Loss : [0.2911]
Epoch:[71/100], Loss : [0.1332]
Epoch:[81/100], Loss : [0.3434]
Epoch:[91/100], Loss : [0.1165]


In [29]:
# device on GPU 인지 혹은 CPU 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device >> ", device)

model.eval()
with torch.no_grad() : 
    correct = 0
    total = 0
    print(len(test_loader))
    for test_inputs, test_targets in test_loader : 
#         print(test_inputs, test_targets)
        test_input, test_target = test_inputs.to(device), test_targets.to(device)
        outputs_test = model(test_input)
        _, pred_test = torch.max(outputs_test, 1)
        # print(pred_test)
        total += test_targets.size(0)
        # print(pred_test)
        # print(test_targets)
        correct += (pred_test == test_targets).sum().item()
        
    print("Acc >> %d%%"%(100 * correct / total))
        

Using device >>  cpu
600
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([1.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([0.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
tensor([0])
tensor([1.])
tensor([0])
tensor([1.])
tensor([0])
tensor([0.])
