In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],  [3,4]]
X_data = torch.tensor(data)

print(X_data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
X_ones = torch.ones_like(X_data)
print(f"ones Tensor: \n{X_ones}")

X_rand =torch.rand_like(X_data, dtype=torch.float)
print(f"Random Tensor: \n{X_rand}")
# torch.ones_like()주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든 요소를 1로 체우면됩니다. 
# torch.rand_like() 주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든 요소를 랜덤한 값으로 채웁니다. 그리고 타입 지정하면 그 타입으로 변경됩니다.

ones Tensor: 
tensor([[1, 1],
        [1, 1]])
Random Tensor: 
tensor([[0.2363, 0.0697],
        [0.7083, 0.7640]])


In [7]:
shape = [5,6, ]
rand_tensor = torch.rand(shape) * 10
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

shape_temp=(5,6)
min_val = 6
max_val = 10
rand_tensor_temp = torch.rand(shape_temp) * (max_val - min_val)
print(rand_tensor_temp)

tensor([[8.1047, 4.2379, 4.9905, 5.7064, 2.2874, 9.9262],
        [7.2533, 6.1393, 6.7410, 6.4961, 9.8198, 4.3603],
        [1.4550, 4.5487, 7.4020, 7.0756, 9.8889, 0.8129],
        [8.0105, 8.5878, 0.1100, 9.4654, 5.5454, 5.8896],
        [3.2944, 8.9029, 3.3287, 5.8982, 4.7509, 4.0627]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[3.0784, 2.9853, 0.7802, 1.1628, 1.5955, 1.0445],
        [3.1955, 0.2381, 1.2406, 0.5323, 3.6636, 1.8006],
        [0.6622, 1.6832, 3.0520, 2.3199, 3.2829, 1.4964],
        [2.3514, 0.4136, 0.4785, 3.5087, 3.7845, 1.1648],
        [3.0949, 1.0798, 3.6089, 1.8756, 0.9784, 1.8903]])


In [8]:
tensor_val = torch.rand(3, 4)
print(f"Shape of tens : {tensor_val.shape}")
print(f"Data : {tensor_val.type}")
print(f"Device tensor is stored on : {tensor_val.device}")

Shape of tens : torch.Size([3, 4])
Data : <built-in method type of Tensor object at 0x000001F1FC33D9F0>
Device tensor is stored on : cpu


Tensor Attribute

In [14]:
tensor_val = torch.rand(3, 4)

dev = 'cuda' if torch.cuda.is_available() else 'cpu'
print("It's ",dev)
tensor_val.to(dev)

print(f"{tensor_val.shape}")
print(tensor_val.dtype)
print(tensor_val.device)

It's  cuda
torch.Size([3, 4])
torch.float32
cpu


In [15]:
tensor_1 = torch.ones(4, 4)
tensor_1[:, 3] = 0
tensor_2 = torch.ones(4, 4)
tensor_2[:, 1] = 2

In [17]:
t1 = torch.cat([tensor_1, tensor_2], dim=1)
print(t1)

tensor([[1., 1., 1., 0., 1., 2., 1., 1.],
        [1., 1., 1., 0., 1., 2., 1., 1.],
        [1., 1., 1., 0., 1., 2., 1., 1.],
        [1., 1., 1., 0., 1., 2., 1., 1.]])


In [19]:
t_mult = tensor_1.mul(tensor_2)
print(t_mult)

print(tensor_1*tensor_2)

tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])
tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])


In [20]:
print(tensor_2.matmul(tensor_2.T))
print(tensor_2 @ tensor_2.T)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [21]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### View - 원소 수 유지하면서 텐서 크기 변경

In [28]:
"""
Pytorch tensor - View is the same with numpy.reshape
"""
    

t_temp = np.array([[[6*i + 3*j + k for k in range(3)] for j in range(2)]for i in range(2)])
ft = torch.FloatTensor(t_temp)

print(ft)
print(ft.shape)

print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
